// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Registro.DAL;

namespace Registro.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200521005517_Migracion_Inicial")]
    partial class Migracion_Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Registro.Models.Errores", b =>
                {
                    b.Property<int>("ErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hallazgo")
                        .HasColumnType("TEXT");

                    b.Property<int>("Importancia")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ruta")
                        .HasColumnType("TEXT");

                    b.HasKey("ErrorId");

                    b.ToTable("Errores");
                });
#pragma warning restore 612, 618
        }
    }
}
